set(INCPLOT_VERSIONDEF_OUTPUT "${INCPLOT_GENERATED_CONFIG_DIR}/auto/versiondef.hpp")
set(INCPLOT_PLATFORM_FOLDER_OUTPUT "${INCPLOT_GENERATED_CONFIG_DIR}/auto/platform_folder.hpp")
file(MAKE_DIRECTORY "${INCPLOT_GENERATED_CONFIG_DIR}/auto")

set(VER_MAJOR ${PROJECT_VERSION_MAJOR})
set(VER_MINOR ${PROJECT_VERSION_MINOR})
set(VER_PATCH ${PROJECT_VERSION_PATCH})

set(INCPLOT_PROJECT_NAME "${PROJECT_NAME}")

if(incplot_PORTABLE_LAYOUT)
    set(INCPLOT_PORTABLE_LAYOUT_BOOL "true")
else()
    set(INCPLOT_PORTABLE_LAYOUT_BOOL "false")
endif()

# Normalize all paths to forward slashes so generated C/C++ string literals are portable.
file(TO_CMAKE_PATH "${CMAKE_INSTALL_PREFIX}" INCPLOT_INSTALL_PREFIX)
file(TO_CMAKE_PATH "${CMAKE_INSTALL_FULL_BINDIR}" INCPLOT_INSTALL_BINDIR)
file(TO_CMAKE_PATH "${CMAKE_INSTALL_FULL_LIBDIR}" INCPLOT_INSTALL_LIBDIR)
file(TO_CMAKE_PATH "${CMAKE_INSTALL_FULL_DATADIR}" INCPLOT_INSTALL_DATADIR)
file(TO_CMAKE_PATH "${CMAKE_INSTALL_FULL_SYSCONFDIR}" INCPLOT_INSTALL_SYSCONFDIR)
file(TO_CMAKE_PATH "${CMAKE_INSTALL_FULL_LOCALSTATEDIR}" INCPLOT_INSTALL_LOCALSTATEDIR)
file(TO_CMAKE_PATH "${CMAKE_INSTALL_FULL_RUNSTATEDIR}" INCPLOT_INSTALL_RUNSTATEDIR)

set(INCPLOT_REL_BINDIR "${CMAKE_INSTALL_BINDIR}")
set(INCPLOT_REL_LIBDIR "${CMAKE_INSTALL_LIBDIR}")
set(INCPLOT_REL_DATAROOTDIR "${CMAKE_INSTALL_DATAROOTDIR}")
set(INCPLOT_REL_DATADIR "${CMAKE_INSTALL_DATADIR}")
set(INCPLOT_REL_SYSCONFDIR "${CMAKE_INSTALL_SYSCONFDIR}")
set(INCPLOT_REL_LOCALSTATEDIR "${CMAKE_INSTALL_LOCALSTATEDIR}")
set(INCPLOT_REL_RUNSTATEDIR "${CMAKE_INSTALL_RUNSTATEDIR}")

configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/config/versiondef.hpp.in"
    "${INCPLOT_VERSIONDEF_OUTPUT}"
    @ONLY)

configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/config/platform_folder.hpp.in"
    "${INCPLOT_PLATFORM_FOLDER_OUTPUT}"
    @ONLY)

set_source_files_properties(
    "${INCPLOT_VERSIONDEF_OUTPUT}"
    "${INCPLOT_PLATFORM_FOLDER_OUTPUT}"
    PROPERTIES
    GENERATED TRUE
    LANGUAGE CXX)

set_source_files_properties(
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/config/versiondef.hpp.in"
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/config/platform_folder.hpp.in"
    PROPERTIES
    HEADER_FILE_ONLY TRUE
    SKIP_LINTING TRUE)
