#pragma once

#ifndef AUTO_VERSIONDEF_H
#define AUTO_VERSIONDEF_H

#define STR_(x) #x
#define STR(x) STR_(x)


#define INCPLOT_VERSION_MAJOR 0
#define INCPLOT_VERSION_MINOR 2
#define INCPLOT_VERSION_PATCH 0

#ifndef INCPLOT_VERSION_MEDIUM
# define INCPLOT_VERSION_MEDIUM "v" STR(INCPLOT_VERSION_MAJOR) \
  "." STR(INCPLOT_VERSION_MINOR) "." STR(INCPLOT_VERSION_PATCH) 
#endif

#endif  // AUTO_VERSIONDEF_H
